Added commands, version check and now throws exception
urrsk/Universal_Robots_Client_Library pull request #1
Opened 2022-11-18 14:31 UTC by urmarp

Added tests for dashboard client

2022-11-21 13:21 UTC, urrsk requested changes
Great job.
Please look at my comments

2022-11-21 13:21 UTC, urrsk commented on examples/dashboard_example.cpp
> +const std::string DEFAULT_ROBOT_IP = "10.53.253.22";
```suggestion
const std::string DEFAULT_ROBOT_IP = "127.0.0.1";
```

2022-11-21 13:21 UTC, urrsk commented on examples/dashboard_example.cpp
> +const std::string DEFAULT_ROBOT_IP = "10.53.253.22";
Suggest reverting this line

2022-11-21 13:21 UTC, urrsk commented on examples/dashboard_example.cpp
> +  my_dashboard->commandCloseSafetyPopup();
Please add a comment on why this is a good idea.
Remember this is an example to get people started

2022-11-21 13:21 UTC, urrsk commented on include/ur_client_library/ur/dashboard_client.h
> +   * \brief Send Is program saved command
```suggestion
   * \brief Send "Is program saved" request command
```

2022-11-21 13:21 UTC, urrsk commented on include/ur_client_library/ur/dashboard_client.h
> +   * \return True succeeded
```suggestion
   * \return True if the program saved
```

2022-11-21 13:21 UTC, urrsk commented on include/ur_client_library/ur/dashboard_client.h
> +   * \brief Send Is in remote control command
```suggestion
   * \brief Send "Is in remote control" request command
```

2022-11-21 13:21 UTC, urrsk commented on include/ur_client_library/ur/dashboard_client.h
> +   * \return True succeeded
```suggestion
   * \return True if it is in remote control
```

2022-11-21 13:21 UTC, urrsk commented on src/ur/dashboard_client.cpp
> +                expected.c_str(), response.c_str());  // Is a warning here so retryCommand does not throw when retrying
Change it to an exception and make "retryCommand()" catch the exception

2022-11-21 13:21 UTC, urrsk commented on src/ur/dashboard_client.cpp
> +    throw UrException("Polyscope software version required is: " + ref + ", but actual version is: " + c);
Will suggest that we throw the exception in the "command" function to make it obvious witch one is the one that is not supported by the robot or pass the command name to this function

2022-11-21 13:21 UTC, urrsk commented on src/ur/dashboard_client.cpp
> +    return false;
Will it ever return false?

2022-11-21 13:21 UTC, urrsk commented on tests/test_dashboard_client.cpp
> +// std::string ROBOT_IP = "192.168.56.101";
Suggest that we remove this line

2022-11-22 08:06 UTC, fmauch commented
I've merged the changes from this PR into https://github.com/UniversalRobots/Universal_Robots_Client_Library/pull/127 and will do the review / final changes there.

2026-02-09 10:34 UTC, closed without merging